### PR TITLE
Index fix

### PR DESCRIPTION
**Pull request by MauriceMohlek**
Clicking on add device in shares will result in a IndexOutOfBounds Exception if there are no shares.

### CODE REVIEW

**Comment by MauriceMohlek** [comment]
Maybe you want to display am error message?
I don't know so i just returned the method.

**Comment by caschulz88** [comment]
Hi,

I guess a better solution is to disable the add button (with a proper message on mouse-over) in case no share has been configured and to enable it once a share has been added.

**Comment by MauriceMohlek** [comment]
Definitely .. 

Nevertheless it gets merged into master, a simple return will fix that "bug" for me now ;-)

Which message should be displayed exactly?
I will add it tomorrow.

**Comment by caschulz88** [comment]
Hi,

I pushed a fix for this problem described in my post above:

https://github.com/Sirrix-AG/PanBox/commit/0e10cffb0c5ac323588e66d980a4c965fa0ca71a

I guess your commit isn't needed then anymore since button will be disabled. You can double-check if the issue is resolved. Feel free to open a new issue or pull request and sorry if I need to close your merge request now, but your MR had some issues:

- The button was still active and user could choose to add device or contact, which makes no sense at all
- As you already said a message was still needed to be added
- We would need to introduce two different error messages for adding device and contact, now we only need one tool-tip message

**Pull request closed without merging**
