### PR TITLE
added travis-ci build

### PR DESCRIPTION
**Pull request by neusdan**
build panbox on linux with travis-ci

https://travis-ci.org/neusdan/PanBox

test execution should be added. don't know how at the moment.

### CODE REVIEW

**Comment by caschulz88** [comment]
Hi, how to include that into github services? Anything special that needs to get added here or just the merge request?

**Comment by neusdan** [comment]
before merge, the project should be connected with the travis ci service at https://travis-ci.org/

**Comment by caschulz88** [comment]
Ok service has been added.

While reviewing your build script I was wondering why not directly calling the ./build_linux.sh script but instead calling the ant builder calls directly? Any advantage?

**Comment by neusdan** [comment]
good point, should be the same :-)

**Pull request merged**
