### PR TITLE
Update CryptCore.java

### PR DESCRIPTION
**Pull request by totalvoidness**
Constant time comparison of checksum

### CODE REVIEW

**Comment by totalvoidness** [comment]
Closing too, as its patching an unused file ;)

**Comment by caschulz88** [comment]
That's not true. The file itself is used in our source code, but some parts aren't. The mentioned method is only used in case export-PIN is used (which is not the case in our current implementation). So the code is not used for now.

To prevent timing attacks we will check if Arrays.equals is used at some other parts. Thanks!

**Comment by totalvoidness** [comment]
Be aware, that MessageDigest's implementation has not been a constant-time implementation in all Java versions though.

If you're building with old JDKs, implement an equals function yourself.



—

**Comment by caschulz88** [comment]
The timing attack vulnerability in MessageDigest was fixed in Java SE 6 Update 17.

PanBox uses at least Java 7 on Linux and on Windows Java 8.

**Comment by totalvoidness** [comment]
reopening as vulnerability still exists, see comments above.

**Comment by caschulz88** [comment]
I'm about to merge this request. But keep in mind that this code is NOT called by any current implementation in PanBox - Since we don't want to remove this extra code for now we will leave it in.

**Pull request merged**
